#!/usr/bin/python

import sys
import subprocess
import re
import os
import glob

DIRECTORY = os.path.join(".", "build", "libs")
FILENAME_RE = r"spongeapi-{}(-SNAPSHOT)?.jar"
VERSION = "1.1" # TODO: I'm lazy
#VERSION = subprocess.check_output("git describe --abbrev=0 --tags", shell=True).strip('v\n')
GIT_COMMIT_DATE = int(subprocess.check_output("git --no-pager show -s --format=%ct", shell=True).strip())

def re_glob(path, pattern):
    return [f for f in os.listdir(path) if pattern.match(f)]

def fail():
    print("Oh ho - trying to push without testing? Shame on you!")
    sys.exit(1)

files = re_glob(DIRECTORY, re.compile(FILENAME_RE.format(VERSION)))
if len(files) > 0:
    t = os.path.getmtime(os.path.join(DIRECTORY, files[0]))
    if t < GIT_COMMIT_DATE:
        fail()
else:
    fail()

print("Congrations! You tested locally!")
sys.exit(0)
